version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

  # Backend server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: acmyx-server
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGODB_URI=mongodb://mongodb:27017/acmyx
      - SESSION_SECRET=${SESSION_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    networks:
      - app-network
    ports:
      - "5001:5001"

  # Frontend client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: acmyx-client
    restart: always
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    networks:
      - app-network
    ports:
      - "80:80"

# Docker networks
networks:
  app-network:
    driver: bridge

# Docker volumes
volumes:
  mongodb_data: 